############# English navigation ##############

# main menu
[[main]]
name = "Beranda"
url = "/"
weight = 1

[[main]]
name = "Tentang"
url = "about/"
weight = 2

[[main]]
name = "Blog"
url = "elements/"
weight = 3


# footer menu
[[footer]]
name = "Jln. Suka Mulia No. 50 Gotong Royong Pangkalan Berandan"
weight = 1
